import Head from "next/head"
import Link from "next/link";
import MyAppBar from "./Components/MyAppBar"

export default function Blog() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyAppBar/>
      <div>
        Blog
      </div>

    </>
  );
}